# Generated by Django 6.0.2 on 2026-02-23 16:45

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('github_username', models.CharField(blank=True, max_length=100)),
                ('github_avatar_url', models.URLField(blank=True, help_text='Avatar URL synced from GitHub')),
                ('huggingface_avatar_url', models.URLField(blank=True, help_text='Avatar URL synced from Hugging Face')),
                ('github_public_repos', models.IntegerField(default=0, help_text='Number of public repos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('github', 'GitHub'), ('huggingface', 'Hugging Face')], max_length=20)),
                ('platform_username', models.CharField(help_text='Username on the platform', max_length=100)),
                ('platform_user_id', models.CharField(blank=True, help_text='User ID on the platform', max_length=100)),
                ('avatar_url', models.URLField(blank=True)),
                ('access_token', models.TextField(help_text='OAuth access token')),
                ('refresh_token', models.TextField(blank=True, help_text='OAuth refresh token if available')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('granted_scopes', models.JSONField(blank=True, default=list, help_text='List of granted OAuth scopes')),
                ('has_repo_scope', models.BooleanField(default=False, help_text='Can star repositories')),
                ('has_write_scope', models.BooleanField(default=False, help_text='Can create repositories')),
                ('is_primary', models.BooleanField(default=False)),
                ('tokens_encrypted', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['github_username'], name='users_custo_github__fe687d_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['created_at'], name='users_custo_created_f4b145_idx'),
        ),
        migrations.AddIndex(
            model_name='userintegration',
            index=models.Index(fields=['user', 'is_primary'], name='users_useri_user_id_b79db4_idx'),
        ),
        migrations.AddIndex(
            model_name='userintegration',
            index=models.Index(fields=['platform'], name='users_useri_platfor_af2618_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userintegration',
            unique_together={('user', 'platform')},
        ),
    ]
