# Generated by Django 6.0.1 on 2026-01-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='github_followers',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_open_to_collaborate',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='github_avatar_url',
            field=models.URLField(blank=True, help_text='Avatar URL synced from GitHub'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='github_public_repos',
            field=models.IntegerField(default=0, help_text='Number of public repos'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='orcid_id',
            field=models.CharField(blank=True, help_text='Researcher ORCID iD', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='research_interests',
            field=models.TextField(blank=True, help_text='Comma-separated interests'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('visitor', 'Visitor'), ('contributor', 'Contributor'), ('researcher', 'Researcher'), ('core_team', 'Core Team')], default='contributor', help_text="User's role in the platform.", max_length=20),
        ),
    ]
