# Generated by Django 6.0.1 on 2026-01-12 16:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_alter_customuser_options_remove_customuser_avatar_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_profile_public',
            field=models.BooleanField(default=True, help_text='Allow others to view your profile'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='orcid_id',
            field=models.CharField(blank=True, help_text='Researcher ORCID iD (format: 0000-0000-0000-000X)', max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid ORCID iD (e.g., 0000-0001-2345-6789)', regex='^\\d{4}-\\d{4}-\\d{4}-\\d{3}[\\dX]$')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='research_interests',
            field=models.JSONField(blank=True, default=list, help_text='List of research topics'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['github_username'], name='users_custo_github__fe687d_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['role'], name='users_custo_role_6a37b1_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['created_at'], name='users_custo_created_f4b145_idx'),
        ),
    ]
