# Generated by Django 6.0.1 on 2026-01-16 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('github', 'GitHub'), ('gitlab', 'GitLab'), ('bitbucket', 'Bitbucket'), ('huggingface', 'Hugging Face')], max_length=20)),
                ('platform_username', models.CharField(help_text='Username on the platform', max_length=100)),
                ('platform_user_id', models.CharField(blank=True, help_text='User ID on the platform', max_length=100)),
                ('avatar_url', models.URLField(blank=True)),
                ('access_token', models.TextField(help_text='OAuth access token')),
                ('refresh_token', models.TextField(blank=True, help_text='OAuth refresh token if available')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('granted_scopes', models.JSONField(blank=True, default=list, help_text='List of granted OAuth scopes')),
                ('has_repo_scope', models.BooleanField(default=False, help_text='Can star repositories')),
                ('has_write_scope', models.BooleanField(default=False, help_text='Can create repositories')),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'is_primary'], name='users_useri_user_id_b79db4_idx'), models.Index(fields=['platform'], name='users_useri_platfor_af2618_idx')],
                'unique_together': {('user', 'platform')},
            },
        ),
    ]
