# Generated by Django 6.0.1 on 2026-01-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_platform_enhancements'),
    ]

    operations = [
        migrations.AddField(
            model_name='userintegration',
            name='tokens_encrypted',
            field=models.BooleanField(default=True),
        ),
    ]
