# Generated by Django 6.0.1 on 2026-01-20 09:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_tokens_encrypted_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='website',
            field=models.URLField(blank=True, help_text='Personal or research website (http/https only)', validators=[django.core.validators.URLValidator(schemes=['http', 'https'])]),
        ),
    ]
