# Generated by Django 6.0.2 on 2026-02-15 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userintegration',
            name='platform',
            field=models.CharField(choices=[('github', 'GitHub'), ('huggingface', 'Hugging Face')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('user_from', 'user_to')},
        ),
    ]
