# Generated by Django 6.0.2 on 2026-02-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_userintegration_platform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='huggingface_avatar_url',
            field=models.URLField(blank=True, help_text='Avatar URL synced from Hugging Face'),
        ),
    ]
