# Generated by Django 6.0.2 on 2026-02-24 12:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(max_length=5000)),
                ('category', models.CharField(choices=[('ai_nlp', 'AI / NLP'), ('ai_vision', 'AI / Computer Vision'), ('data_science', 'Data Science'), ('web_tools', 'Web Tools'), ('ai_audio', 'AI / Audio & Speech'), ('ml_ops', 'MLOps / Infra'), ('robotics', 'Robotics'), ('research', 'Research'), ('other', 'Other')], default='other', max_length=50)),
                ('github_repo_url', models.URLField(help_text='URL to the GitHub repository')),
                ('demo_url', models.URLField(blank=True, help_text='Live demo URL (e.g. Vercel/Cloudflare deployment)', null=True)),
                ('huggingface_url', models.URLField(blank=True, help_text='Link to Hugging Face model/dataset', null=True)),
                ('stars_count', models.IntegerField(default=0)),
                ('forks_count', models.IntegerField(default=0)),
                ('view_count', models.IntegerField(default=0)),
                ('language', models.CharField(blank=True, max_length=50)),
                ('topics', models.JSONField(blank=True, default=list)),
                ('is_hot', models.BooleanField(default=False, help_text="Automated 'HOT' status based on engagement")),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(help_text='AI-generated 2-3 sentence summary')),
                ('tech_stack', models.JSONField(default=list, help_text='Detected languages and frameworks')),
                ('complexity_score', models.IntegerField(default=5, help_text='1-10 rating of code complexity', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('complexity_reason', models.TextField(blank=True, help_text='Why this score was given')),
                ('use_cases', models.JSONField(blank=True, default=list, help_text='Practical use cases')),
                ('strengths', models.JSONField(blank=True, default=list, help_text='Notable strengths')),
                ('suggestions', models.JSONField(blank=True, default=list, help_text='Improvement suggestions')),
                ('last_analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('ai_model_used', models.CharField(blank=True, default='', max_length=100)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insight', to='projects.project')),
            ],
            options={
                'ordering': ['-last_analyzed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_approved', 'is_hot'], name='projects_pr_is_appr_f8cbaa_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_approved', '-stars_count'], name='projects_pr_is_appr_c6690d_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_approved', '-created_at'], name='projects_pr_is_appr_efcec3_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['submitted_by'], name='projects_pr_submitt_6f3756_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['slug'], name='projects_pr_slug_042165_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['category'], name='projects_pr_categor_220446_idx'),
        ),
        migrations.AddIndex(
            model_name='projectinsight',
            index=models.Index(fields=['complexity_score'], name='projects_pr_complex_a37a45_idx'),
        ),
    ]
