# Generated by Django 6.0.2 on 2026-02-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(max_length=5000)),
                ('category', models.CharField(choices=[('ai_nlp', 'AI / NLP'), ('ai_vision', 'AI / Computer Vision'), ('data_science', 'Data Science'), ('web_tools', 'Web Tools'), ('ai_audio', 'AI / Audio & Speech'), ('ml_ops', 'MLOps / Infra'), ('robotics', 'Robotics'), ('research', 'Research'), ('other', 'Other')], default='other', max_length=50)),
                ('github_repo_url', models.URLField(help_text='URL to the GitHub repository')),
                ('demo_url', models.URLField(blank=True, help_text='Live demo URL (e.g. Vercel/Cloudflare deployment)', null=True)),
                ('huggingface_url', models.URLField(blank=True, help_text='Link to Hugging Face model/dataset')),
                ('stars_count', models.IntegerField(default=0)),
                ('forks_count', models.IntegerField(default=0)),
                ('view_count', models.IntegerField(default=0)),
                ('language', models.CharField(blank=True, max_length=50)),
                ('topics', models.JSONField(blank=True, default=list)),
                ('is_hot', models.BooleanField(default=False, help_text="Automated 'HOT' status based on engagement")),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(help_text='AI-generated 2-3 sentence summary')),
                ('tech_stack', models.JSONField(default=list, help_text='Detected languages and frameworks')),
                ('complexity_score', models.IntegerField(default=5, help_text='1-10 rating of code complexity')),
                ('complexity_reason', models.TextField(blank=True, help_text='Why this score was given')),
                ('improvements', models.JSONField(default=list, help_text='List of suggested code improvements')),
                ('roadmap', models.JSONField(default=list, help_text='Suggested next steps/features')),
                ('last_analyzed_at', models.DateTimeField(auto_now=True)),
                ('ai_model_used', models.CharField(default='gemini-2.5-flash', max_length=50)),
            ],
            options={
                'ordering': ['-last_analyzed_at'],
            },
        ),
    ]
