# Generated by Django 6.0.2 on 2026-02-24 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='projectinsight',
            name='projects_pr_complex_a37a45_idx',
        ),
        migrations.DeleteModel(
            name='ProjectInsight',
        ),
    ]
