# Generated by Django 6.0.2 on 2026-02-23 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectinsight',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insight', to='projects.project'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_approved', 'is_hot'], name='projects_pr_is_appr_f8cbaa_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_approved', '-stars_count'], name='projects_pr_is_appr_c6690d_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_approved', '-created_at'], name='projects_pr_is_appr_efcec3_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['submitted_by'], name='projects_pr_submitt_6f3756_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['slug'], name='projects_pr_slug_042165_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['category'], name='projects_pr_categor_220446_idx'),
        ),
        migrations.AddIndex(
            model_name='projectinsight',
            index=models.Index(fields=['complexity_score'], name='projects_pr_complex_a37a45_idx'),
        ),
    ]
