# Generated by Django 6.0.1 on 2026-01-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.RemoveField(
            model_name='project',
            name='documentation_url',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='project',
            name='open_issues_count',
        ),
        migrations.AddField(
            model_name='project',
            name='is_hot',
            field=models.BooleanField(default=False, help_text="Automated 'HOT' status based on engagement"),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('ai_nlp', 'AI / NLP'), ('ai_vision', 'AI / Computer Vision'), ('data_science', 'Data Science'), ('web_tools', 'Web Tools'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='huggingface_url',
            field=models.URLField(blank=True, default='', help_text='Link to Hugging Face model/dataset'),
        ),
        migrations.AlterField(
            model_name='project',
            name='topics',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='project',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
