# Generated by Django 6.0.1 on 2026-01-12 16:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('ai_nlp', 'AI / NLP'), ('ai_vision', 'AI / Computer Vision'), ('data_science', 'Data Science'), ('web_tools', 'Web Tools'), ('ai_audio', 'AI / Audio & Speech'), ('ml_ops', 'MLOps / Infra'), ('robotics', 'Robotics'), ('research', 'Research'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='project',
            name='huggingface_url',
            field=models.URLField(blank=True, help_text='Link to Hugging Face model/dataset'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_approved', 'is_hot'], name='projects_pr_is_appr_f8cbaa_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_approved', '-stars_count'], name='projects_pr_is_appr_c6690d_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_approved', '-created_at'], name='projects_pr_is_appr_efcec3_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['submitted_by'], name='projects_pr_submitt_6f3756_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['slug'], name='projects_pr_slug_042165_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['category'], name='projects_pr_categor_220446_idx'),
        ),
    ]
