# Generated by Django 6.0.1 on 2026-01-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_options_alter_project_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='execution_url',
            field=models.URLField(blank=True, help_text='Magic link for Binder/Colab', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='gist_id',
            field=models.CharField(blank=True, help_text='GitHub Gist ID for Binder/Colab config', max_length=64),
        ),
        migrations.AddField(
            model_name='project',
            name='lane',
            field=models.CharField(choices=[('A', 'Client-Side (WebContainer)'), ('B', 'Cloud Container (Binder)'), ('C', 'GPU Cluster (Colab)'), ('P', 'Pending Classification')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='project',
            name='lane_classification_reason',
            field=models.TextField(blank=True, help_text='AI explanation for lane choice'),
        ),
        migrations.AddField(
            model_name='project',
            name='start_command',
            field=models.CharField(blank=True, help_text='e.g., npm run dev, python manage.py runserver', max_length=255),
        ),
    ]
