# Generated by Django 6.0.1 on 2026-01-20 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_traffic_controller_lanes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(help_text='AI-generated 2-3 sentence summary')),
                ('tech_stack', models.JSONField(default=list, help_text='Detected languages and frameworks')),
                ('complexity_score', models.IntegerField(default=5, help_text='1-10 rating of code complexity')),
                ('complexity_reason', models.TextField(blank=True, help_text='Why this score was given')),
                ('improvements', models.JSONField(default=list, help_text='List of suggested code improvements')),
                ('roadmap', models.JSONField(default=list, help_text='Suggested next steps/features')),
                ('last_analyzed_at', models.DateTimeField(auto_now=True)),
                ('ai_model_used', models.CharField(default='gemini-2.5-flash', max_length=50)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insight', to='projects.project')),
            ],
            options={
                'ordering': ['-last_analyzed_at'],
                'indexes': [models.Index(fields=['complexity_score'], name='projects_pr_complex_a37a45_idx')],
            },
        ),
    ]
