# Generated by Django 6.0.2 on 2026-02-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_add_project_insight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='lane',
            field=models.CharField(choices=[('P', 'PyStudio (Python/WASM)'), ('J', 'JS Studio (Node/WebContainer)'), ('B', 'Cloud Container (Binder)'), ('C', 'GPU Cluster (Colab)'), ('?', 'Pending Classification')], default='?', max_length=1),
        ),
    ]
