# Generated by Django 6.0.2 on 2026-02-23 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EcosystemPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('icon_class', models.CharField(help_text="FontAwesome or custom icon class, e.g. 'fas fa-store'", max_length=100)),
                ('short_description', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Ecosystem Platform',
                'verbose_name_plural': 'Ecosystem Platforms',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('error', 'Error'), ('warning', 'Warning'), ('info', 'Info')], default='error', max_length=10)),
                ('path', models.CharField(help_text='Request path where error occurred', max_length=500)),
                ('method', models.CharField(default='GET', max_length=10)),
                ('exception_type', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField(help_text='Error message')),
                ('traceback', models.TextField(blank=True, help_text='Full traceback')),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='core_errorl_created_3e37bc_idx'), models.Index(fields=['level', '-created_at'], name='core_errorl_level_fe3ed5_idx'), models.Index(fields=['is_resolved', '-created_at'], name='core_errorl_is_reso_8d538a_idx')],
            },
        ),
    ]
