# Generated by Django 6.0.1 on 2026-01-20 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_platform_enhancements'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('error', 'Error'), ('warning', 'Warning'), ('info', 'Info')], default='error', max_length=10)),
                ('path', models.CharField(help_text='Request path where error occurred', max_length=500)),
                ('method', models.CharField(default='GET', max_length=10)),
                ('exception_type', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField(help_text='Error message')),
                ('traceback', models.TextField(blank=True, help_text='Full traceback')),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='core_errorl_created_3e37bc_idx'), models.Index(fields=['level', '-created_at'], name='core_errorl_level_fe3ed5_idx'), models.Index(fields=['is_resolved', '-created_at'], name='core_errorl_is_reso_8d538a_idx')],
            },
        ),
    ]
