# Generated by Django 5.2.9 on 2026-01-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('abstract', models.TextField(help_text='A brief summary of the research paper.')),
                ('content', models.TextField(help_text='The main content in Markdown format.')),
                ('executable_script', models.TextField(blank=True, help_text='JavaScript/Python code for interactive demo (runs via Pyodide/Transformers.js)')),
                ('arxiv_id', models.CharField(blank=True, help_text='arXiv paper ID (e.g., 2301.00001)', max_length=20)),
                ('doi', models.CharField(blank=True, help_text='Digital Object Identifier', max_length=100)),
                ('bibtex', models.TextField(blank=True, help_text='BibTeX citation entry')),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
