# Generated by Django 5.2.9 on 2026-01-12 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publication',
            name='contributors',
            field=models.ManyToManyField(blank=True, help_text='Additional contributors (CRediT taxonomy)', related_name='contributed_publications', to=settings.AUTH_USER_MODEL),
        ),
    ]
