# Generated by Django 6.0.1 on 2026-01-12 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={},
        ),
        migrations.RemoveField(
            model_name='publication',
            name='doi',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='published_at',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='view_count',
        ),
        migrations.AlterField(
            model_name='publication',
            name='abstract',
            field=models.TextField(help_text='Brief summary.'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='arxiv_id',
            field=models.CharField(blank=True, help_text='arXiv ID if applicable', max_length=20),
        ),
        migrations.AlterField(
            model_name='publication',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_publications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publication',
            name='bibtex',
            field=models.TextField(blank=True, help_text='BibTeX citation'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='content',
            field=models.TextField(help_text='Main content in Markdown.'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='contributors',
            field=models.ManyToManyField(blank=True, related_name='contributed_publications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publication',
            name='executable_script',
            field=models.TextField(blank=True, help_text='Python/JS code for in-browser execution (Pyodide).'),
        ),
    ]
