# Generated by Django 6.0.1 on 2026-01-12 16:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_alter_publication_options_remove_publication_doi_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['is_published', '-created_at'], name='publication_is_publ_372944_idx'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['author'], name='publication_author__c579c6_idx'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['slug'], name='publication_slug_c19642_idx'),
        ),
    ]
