# Generated by Django 6.0.1 on 2026-01-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_alter_publication_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
