# Generated by Django 6.0.1 on 2026-01-12 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0005_publication_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='bibtex',
        ),
        migrations.AddField(
            model_name='publication',
            name='doi',
            field=models.CharField(blank=True, help_text='Digital Object Identifier', max_length=100),
        ),
        migrations.AlterField(
            model_name='publication',
            name='arxiv_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='PublicationRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='publications.publication')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
    ]
