# Generated by Django 6.0.1 on 2026-01-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0006_remove_publication_bibtex_publication_doi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='github_file_path',
            field=models.CharField(blank=True, help_text='Path to the markdown file within the repo.', max_length=255),
        ),
        migrations.AddField(
            model_name='publication',
            name='github_repo_url',
            field=models.CharField(blank=True, help_text='URL to the GitHub repository storing content.', max_length=255),
        ),
    ]
