# Generated by Django 6.0.2 on 2026-02-15 06:36

import publications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0007_publication_github_file_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='github_file_path',
            field=models.CharField(blank=True, help_text='Path to the markdown file within the repo (e.g. docs/paper.md).', max_length=255, validators=[publications.models.validate_path_traversal]),
        ),
        migrations.AlterField(
            model_name='publication',
            name='github_repo_url',
            field=models.URLField(blank=True, help_text='URL to the GitHub repository storing content.', max_length=255),
        ),
        migrations.AddConstraint(
            model_name='publicationrevision',
            constraint=models.UniqueConstraint(fields=('publication', 'version'), name='unique_publication_version'),
        ),
    ]
