# Generated by Django 6.0.2 on 2026-02-15 06:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0001_initial'),
        ('projects', '0006_add_project_insight'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['category'], name='discussions_categor_5afc60_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['-is_pinned', '-created_at'], name='discussions_is_pinn_e69f13_idx'),
        ),
    ]
